name: Code Quality Pull Request
on:
  workflow_dispatch:
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'maven'
      - name: Validate Maven Wrapper
        run: mvn --version
      - name: Run Tests
        run: mvn test
        env:
          USER_NAME: ${{ secrets.GH_PIPELINE_USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.GH_PIPELINE_TOKEN }}
      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: maven-coverage-data
          path: .qodana/code-coverage
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: true
          args: -e,USER_NAME=${{ secrets.GH_PIPELINE_USER_NAME }},-e,ACCESS_TOKEN=${{ secrets.GH_PIPELINE_TOKEN }}
