name: Code Review Comment
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    outputs:
      commentOut: ${{ steps.get-comment.outputs.comment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get comment text from URL
        id: get-comment
        run: |
          {
            echo 'comment<<EOF'
            curl -sL https://raw.githubusercontent.com/DataMigration-International-AG/.github/development/code_review_checklist.md
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Add comment to PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `${{ steps.get-comment.outputs.comment }}`;
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            
            github.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });
