package com.datamigration.jds.util;

public interface ITestSQLs {

	String TRUNCATE_DB = """
		IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'JIVS-DOCSTORE')
			DELETE FROM [jds].[JIVS-DOCSTORE];
		IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'JIVS-DOCUMENT-PARAM')
			DELETE FROM [jds].[JIVS-DOCUMENT-PARAM]
		""";

	String SELECT_DOCUMENT_BY_ID_SQL = """
		SELECT ID, FILENAME, CREATOR, DELETED
		FROM [jds].[JIVS-DOCSTORE]
		WHERE ID = ?
		AND DELETED = 0
		""";

	String SELECT_DOCUMENT_BY_FILE_NAME_SQL = """
		SELECT ID, FILENAME, CREATOR, DELETED
		FROM [jds].[JIVS-DOCSTORE]
		WHERE FILENAME = ?
		""";

	String SELECT_DOCUMENT_BY_DOCUMENT_TYPE_SQL = """
		SELECT ID, [DOCUMENT-TYPE]
		FROM [jds].[JIVS-DOCSTORE]
		WHERE [DOCUMENT-TYPE] = ?
		AND DELETED = 0
		""";

	String SELECT_DOCUMENT_BY_CREATOR_SQL = """
		SELECT ID, CREATOR
		FROM [jds].[JIVS-DOCSTORE]
		WHERE CREATOR = ?
		AND DELETED = 0
		""";

	String SELECT_DOCUMENT_BY_CUSTOMER_FK_SQL = """
		SELECT ID, [CUSTOMER-FK]
		FROM [jds].[JIVS-DOCSTORE]
		WHERE [CUSTOMER-FK] = ?
		AND DELETED = 0
		""";

	String SELECT_DOCUMENT_BY_SYSTEM_FK_SQL = """
		SELECT ID, [SYSTEM-FK]
		FROM [jds].[JIVS-DOCSTORE]
		WHERE [SYSTEM-FK] = ?
		AND DELETED = 0
		""";

	String SELECT_DOCUMENT_BY_CASE_ID_SQL = """
		SELECT ID, [CASE-ID]
		FROM [jds].[JIVS-DOCSTORE]
		WHERE [CASE-ID] = ?
		AND DELETED = 0
		""";

	String SELECT_ALL_DOCUMENT_PARAMS_BY_DOCUMENT_ID_SQL = """
		SELECT [DOCUMENT-ID], [KEY], [VALUE]
		FROM [jds].[JIVS-DOCUMENT-PARAM]
		WHERE [DOCUMENT-ID] = ?
		""";
}
